// <auto-generated />
using Labeling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Labeling.Infrastructure.Migrations
{
    [DbContext(typeof(LabelingDbContext))]
    partial class LabelingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Exim.T4d.Labeling.Domain.GuaranteeDebt.GuaranteeDebt", b =>
                {
                    b.Property<decimal>("DebtIdpk")
                        .HasColumnType("numeric")
                        .HasColumnName("debt_idpk");

                    b.Property<string>("CurrencyDesc")
                        .HasMaxLength(53)
                        .HasColumnType("character varying(53)")
                        .HasColumnName("currency_desc");

                    b.Property<string>("CusNameTh")
                        .HasMaxLength(61)
                        .HasColumnType("character varying(61)")
                        .HasColumnName("cus_name_th");

                    b.Property<decimal?>("CustId")
                        .HasColumnType("numeric")
                        .HasColumnName("cust_id");

                    b.Property<string>("CustName")
                        .HasMaxLength(68)
                        .HasColumnType("character varying(68)")
                        .HasColumnName("custname");

                    b.Property<string>("DateFrom")
                        .HasMaxLength(69)
                        .HasColumnType("character varying(69)")
                        .HasColumnName("date_from");

                    b.Property<string>("DateTo")
                        .HasMaxLength(69)
                        .HasColumnType("character varying(69)")
                        .HasColumnName("date_to");

                    b.Property<string>("DueDate")
                        .HasMaxLength(69)
                        .HasColumnType("character varying(69)")
                        .HasColumnName("due_date");

                    b.Property<string>("FeeAmount")
                        .HasMaxLength(54)
                        .HasColumnType("character varying(54)")
                        .HasColumnName("fee_amount");

                    b.Property<decimal?>("GrtIdpk")
                        .HasColumnType("numeric")
                        .HasColumnName("grt_idpk");

                    b.Property<string>("InterestAmount")
                        .HasMaxLength(54)
                        .HasColumnType("character varying(54)")
                        .HasColumnName("interest_amount");

                    b.Property<string>("LetterNo")
                        .HasMaxLength(67)
                        .HasColumnType("character varying(67)")
                        .HasColumnName("letter_no");

                    b.Property<string>("LimitDesc")
                        .HasMaxLength(74)
                        .HasColumnType("character varying(74)")
                        .HasColumnName("limit_desc");

                    b.Property<decimal?>("LimitId")
                        .HasColumnType("numeric")
                        .HasColumnName("limit_id");

                    b.Property<decimal?>("Nb")
                        .HasColumnType("numeric")
                        .HasColumnName("nb");

                    b.Property<decimal?>("PrincipleAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("principle_amount");

                    b.Property<string>("Reference")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference");

                    b.Property<string>("TypeCust")
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("typecust");

                    b.HasKey("DebtIdpk");

                    b.HasIndex("GrtIdpk");

                    b.ToTable("guarantee_debt", "T4D_DEV");
                });

            modelBuilder.Entity("Exim.T4d.Labeling.Domain.GuaranteeInfo.GuaranteeInfo", b =>
                {
                    b.Property<decimal>("GrtIdpk")
                        .HasColumnType("numeric")
                        .HasColumnName("grt_idpk");

                    b.Property<string>("AddrNo")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("addr_no");

                    b.Property<string>("AddressProvince")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("address_province");

                    b.Property<string>("ConDate")
                        .HasMaxLength(69)
                        .HasColumnType("character varying(69)")
                        .HasColumnName("con_date");

                    b.Property<string>("ContractSignDate")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("contract_sign_date");

                    b.Property<string>("CusNameTh")
                        .HasMaxLength(61)
                        .HasColumnType("character varying(61)")
                        .HasColumnName("cus_name_th");

                    b.Property<decimal?>("CustId")
                        .HasColumnType("numeric")
                        .HasColumnName("cust_id");

                    b.Property<string>("CustName")
                        .HasMaxLength(65)
                        .HasColumnType("character varying(65)")
                        .HasColumnName("custname");

                    b.Property<string>("DateNow")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("datenow");

                    b.Property<string>("District")
                        .HasMaxLength(68)
                        .HasColumnType("character varying(68)")
                        .HasColumnName("district");

                    b.Property<string>("GrtName")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("grt_name");

                    b.Property<string>("LetterNo")
                        .HasMaxLength(67)
                        .HasColumnType("character varying(67)")
                        .HasColumnName("letter_no");

                    b.Property<string>("LimitDesc")
                        .HasMaxLength(74)
                        .HasColumnType("character varying(74)")
                        .HasColumnName("limit_desc");

                    b.Property<decimal?>("LimitId")
                        .HasColumnType("numeric")
                        .HasColumnName("limit_id");

                    b.Property<string>("TypeCust")
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("typecust");

                    b.HasKey("GrtIdpk");

                    b.ToTable("guarantee_info", "T4D_DEV");
                });

            modelBuilder.Entity("Exim.T4d.Labeling.Domain.GuaranteeDebt.GuaranteeDebt", b =>
                {
                    b.HasOne("Exim.T4d.Labeling.Domain.GuaranteeInfo.GuaranteeInfo", null)
                        .WithMany("GuaranteeDebts")
                        .HasForeignKey("GrtIdpk");
                });

            modelBuilder.Entity("Exim.T4d.Labeling.Domain.GuaranteeInfo.GuaranteeInfo", b =>
                {
                    b.Navigation("GuaranteeDebts");
                });
#pragma warning restore 612, 618
        }
    }
}
