// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reporting.Infrastructure.Persistence;

#nullable disable

#pragma warning disable IDE0161

namespace Reporting.Infrastructure.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260807091325_AddScheduledReports")]
    partial class AddScheduledReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reporting.Domain.RenderLogs.RenderLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DataSourceExecutionMs")
                        .HasColumnType("bigint");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("OutputSizeBytes")
                        .HasColumnType("integer");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb");

                    b.Property<long?>("RenderMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("TemplateBindingMs")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ReportDefinitionId");

                    b.HasIndex("StartedAt");

                    b.ToTable("render_logs", "reporting");
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportDataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionStringName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DataSourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportDefinitionId", "Name")
                        .IsUnique();

                    b.ToTable("report_data_sources", "reporting");
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportDataSourceParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DbType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ReportDataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportParameterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceParameterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ReportDataSourceId", "SourceParameterName")
                        .IsUnique();

                    b.ToTable("report_data_source_parameters", "reporting");
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("ExecutionTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxRowCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplatePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Name")
                        .IsUnique();

                    b.ToTable("report_definitions", "reporting");
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationRuleJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ReportDefinitionId", "Name")
                        .IsUnique();

                    b.ToTable("report_parameters", "reporting");
                });

            modelBuilder.Entity("Reporting.Domain.ReportExecutions.ReportExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BatchItemIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("OutputFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RenderMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("_requestedFormats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("requested_formats");

                    b.HasKey("Id");

                    b.HasIndex("BatchExecutionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReportDefinitionId");

                    b.HasIndex("Status");

                    b.HasIndex("TriggeredBy");

                    b.ToTable("report_executions", "reporting");
                });

            modelBuilder.Entity("Reporting.Domain.ReportExecutions.ReportOutputFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ReportExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ReportExecutionId");

                    b.ToTable("report_output_files", "reporting");
                });

            modelBuilder.Entity("Reporting.Domain.ReportSchedules.ScheduledReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedFormatsCsv")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ScheduleType");

                    b.HasIndex("ReportDefinitionId", "ScheduleType");

                    b.ToTable("scheduled_reports", "reporting");
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportDataSource", b =>
                {
                    b.HasOne("Reporting.Domain.ReportDefinitions.ReportDefinition", null)
                        .WithMany("DataSources")
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportDataSourceParameter", b =>
                {
                    b.HasOne("Reporting.Domain.ReportDefinitions.ReportDataSource", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ReportDataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportParameter", b =>
                {
                    b.HasOne("Reporting.Domain.ReportDefinitions.ReportDefinition", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Domain.ReportExecutions.ReportOutputFile", b =>
                {
                    b.HasOne("Reporting.Domain.ReportExecutions.ReportExecution", null)
                        .WithMany("OutputFiles")
                        .HasForeignKey("ReportExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Domain.ReportSchedules.ScheduledReport", b =>
                {
                    b.HasOne("Reporting.Domain.ReportDefinitions.ReportDefinition", null)
                        .WithMany()
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportDataSource", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Reporting.Domain.ReportDefinitions.ReportDefinition", b =>
                {
                    b.Navigation("DataSources");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Reporting.Domain.ReportExecutions.ReportExecution", b =>
                {
                    b.Navigation("OutputFiles");
                });
#pragma warning restore 612, 618
        }

#pragma warning restore IDE0161
    }
}
